[project]
name = "coding-challenges"
version = "0.1.0"
description = ""
authors = ["edmondburnett <_@edmondburnett.com>"]
requires-python = ">=3.13.7, <3.14"

[dependency-groups]
dev = [
    "basedpyright>=1.36.2",
    "ipython>=9.8.0",
    "neovim>=0.3.1",
    "ruff>=0.14.10",
]
